title: Juan David Padilla
logo: foto circulo.png
description: Professional in Finance and International Relations, corporate finance, Data Analysis and visualization Python, Rstudio, SQL, Java, PowerBI, Tableau, Looker Studio
Linkedin: (www.linkedin.com/in/juandapalo2)
#show_downloads:true
theme: jekyll-theme-minimal

