title: Juan David Padilla
logo: foto circulo.png
description: Profesional en Finanzas y Relaciones Internacionales, Análisis y Visualización de Datos y Finanzas Corporativas | Python, Rstudio, SQL, PowerBI, Tableau
#show_downloads:true
theme: jekyll-theme-minimal

